module.exports = {

  AUTH_SIGNIN_FAIL: 'AUTH_SIGNIN_FAIL',
  AUTH_CHANGED: 'AUTH_CHANGED',

  CARD_CHANGED: 'CARD_CHANGED',
  CARD_TAKE_MONEY_SUCCESS: 'CARD_TAKE_MONEY_SUCCESS',
  CARD_TAKE_MONEY_FAIL: 'CARD_TAKE_MONEY_FAIL',

  REQUEST_FAIL: 'REQUEST_FAIL'
};
