module.exports = {

  AUTH_SIGNIN: 'AUTH_SIGNIN',
  AUTH_SIGNIN_SUCCESS: 'AUTH_SIGNIN_SUCCESS',
  AUTH_SIGNIN_FAIL: 'AUTH_SIGNIN_FAIL',

  CARD_FETCH: 'CARD_FETCH',
  CARD_CHANGED: 'CARD_CHANGED',
  CARD_TAKE_MONEY_SUCCESS: 'CARD_TAKE_MONEY_SUCCESS',
  CARD_TAKE_MONEY_FAIL: 'CARD_TAKE_MONEY_FAIL',

  REQUEST_FAIL: 'REQUEST_FAIL'
};
