module.exports = {

  // Route action types
  SET_CURRENT_ROUTE: 'SET_CURRENT_ROUTE',

  AUTH_SIGNIN: 'AUTH_SIGNIN',
  AUTH_SIGNIN_SUCCESS: 'AUTH_SIGNIN_SUCCESS',
  AUTH_SIGNIN_FAIL: 'AUTH_SIGNIN_FAIL'
};
